"""NodeTree storage helpers for source code, scratch text, and group reset."""

import bpy

SOURCE_PROP = "gn_script_mvp_source"
SOURCE_VERSION_PROP = "gn_script_mvp_source_version"
INPUT_DEFAULTS_PROP = "gn_script_mvp_input_defaults"
DESCRIPTION_PREFIX = "Generated by NodeForge from:\n"
LEGACY_DESCRIPTION_PREFIX = "Generated by GN Script MVP from: "
SCRATCH_TEXT_NAME = "NodeForge_Current"

def _reset_node_group(group):
    """Clear a GeometryNodeTree in-place so existing Group nodes keep pointing to it."""
    # Remove links first, then nodes.
    try:
        group.links.clear()
    except Exception:
        pass
    for node in list(group.nodes):
        group.nodes.remove(node)
    # Remove interface sockets/panels. items_tree is flat in Blender 4+/5+.
    try:
        for item in reversed(list(group.interface.items_tree)):
            try:
                group.interface.remove(item)
            except Exception:
                pass
    except Exception:
        pass

def _store_group_source(group, source: str):
    """Store source code on the node group and expose it in the tooltip with line breaks."""
    src = source or ""
    group[SOURCE_PROP] = src
    group[SOURCE_VERSION_PROP] = "0.24"
    # Keep custom property as canonical storage, but make Blender tooltip readable.
    # Newlines are preserved so hovering a group node shows the original script layout.
    preview = src.strip()
    if len(preview) > 1800:
        preview = preview[:1797] + "..."
    group.description = DESCRIPTION_PREFIX + preview

def _extract_group_source(group):
    """Function `_extract_group_source` used by the NodeForge addon."""
    if group is None:
        return ""
    try:
        src = group.get(SOURCE_PROP, "")
    except Exception:
        src = ""
    if isinstance(src, str) and src:
        return src
    desc = getattr(group, "description", "") or ""
    if desc.startswith(DESCRIPTION_PREFIX):
        return desc[len(DESCRIPTION_PREFIX):]
    if desc.startswith(LEGACY_DESCRIPTION_PREFIX):
        return desc[len(LEGACY_DESCRIPTION_PREFIX):]
    return ""

def _get_or_create_scratch_text():
    """Function `_get_or_create_scratch_text` used by the NodeForge addon."""
    text = bpy.data.texts.get(SCRATCH_TEXT_NAME)
    if text is None:
        text = bpy.data.texts.new(SCRATCH_TEXT_NAME)
    return text

def _replace_text_contents(text, source: str):
    """Function `_replace_text_contents` used by the NodeForge addon."""
    text.clear()
    text.write(source or "")

__all__ = ['_reset_node_group', '_store_group_source', '_extract_group_source', '_get_or_create_scratch_text', '_replace_text_contents']
