"""NodeTree storage helpers for source code, scratch text, and group reset."""

import bpy

SOURCE_PROP = "gn_script_mvp_source"
SOURCE_VERSION_PROP = "gn_script_mvp_source_version"
INPUT_DEFAULTS_PROP = "gn_script_mvp_input_defaults"
DESCRIPTION_PREFIX = "Generated by GN Script MVP from: "
SCRATCH_TEXT_NAME = "GNScriptMVP_Current"

def _reset_node_group(group):
    """Clear a GeometryNodeTree in-place so existing Group nodes keep pointing to it."""
    # Remove links first, then nodes.
    try:
        group.links.clear()
    except Exception:
        pass
    for node in list(group.nodes):
        group.nodes.remove(node)
    # Remove interface sockets/panels. items_tree is flat in Blender 4+/5+.
    try:
        for item in reversed(list(group.interface.items_tree)):
            try:
                group.interface.remove(item)
            except Exception:
                pass
    except Exception:
        pass

def _store_group_source(group, source: str):
    """Function `_store_group_source` used by the GN Script MVP addon."""
    src = source or ""
    group[SOURCE_PROP] = src
    group[SOURCE_VERSION_PROP] = "0.16"
    # Keep tooltip useful but avoid relying on it as the canonical storage.
    one_line = " ".join(src.strip().split())
    if len(one_line) > 900:
        one_line = one_line[:897] + "..."
    group.description = DESCRIPTION_PREFIX + one_line

def _extract_group_source(group):
    """Function `_extract_group_source` used by the GN Script MVP addon."""
    if group is None:
        return ""
    try:
        src = group.get(SOURCE_PROP, "")
    except Exception:
        src = ""
    if isinstance(src, str) and src:
        return src
    desc = getattr(group, "description", "") or ""
    if desc.startswith(DESCRIPTION_PREFIX):
        return desc[len(DESCRIPTION_PREFIX):]
    return ""

def _get_or_create_scratch_text():
    """Function `_get_or_create_scratch_text` used by the GN Script MVP addon."""
    text = bpy.data.texts.get(SCRATCH_TEXT_NAME)
    if text is None:
        text = bpy.data.texts.new(SCRATCH_TEXT_NAME)
    return text

def _replace_text_contents(text, source: str):
    """Function `_replace_text_contents` used by the GN Script MVP addon."""
    text.clear()
    text.write(source or "")

__all__ = ['_reset_node_group', '_store_group_source', '_extract_group_source', '_get_or_create_scratch_text', '_replace_text_contents']
